- hosts: all
  vars:
  - x : "{{  ansible_facts['distribution'] }}"
  tasks:
  - package:
      name: "httpd"
    when: x == "RedHat"
  - package:
      name: "apache2"
    when: x == "Debian"
  - debug:
      msg: "{{ x }}"
  - debug:
      msg: "{{ ansible_facts['distribution'] }}"
  - debug:
      var: "x"
  - service:
      name: "httpd"
      state: "started"
    register: y
  - debug:
      var: y
  - debug:
      msg: "Yayy"
    when: y.changed == False or y.failed == false
  - command: date
